language: python

python:
    - "3.5"
    - "3.6"

cache: pip

install:
    - pip install -r requirements.txt
    - pip install codecov
    - export PYTHONPATH=.

script:
  - ./scripts/lint --flake8
  - ./scripts/test --cov

after_success:
    - codecov
